//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektZaliczeniwyProgramowanie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ReciveDate { get; set; }
        public int CarrierID { get; set; }
        public int RecipientID { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual Product Product { get; set; }
        public virtual Recipient Recipient { get; set; }
    }
}
